{% set name = "highspy" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/highspy-{{ version }}.tar.gz
  url: https://github.com/ERGO-Code/HiGHS/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a0d09371fadb56489497996b28433be1ef91a705e3811fcb1f50a107c7d427d1
  patches:
    - patches/0001-Got-error-about-missing-std-tolower-on-MSVC.patch

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  ignore_run_exports:
    - numpy

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - python
    - pip
    - scikit-build-core
    - numpy
    - pybind11
  run:
    - python
    - numpy

test:
  files:
    - tests
  imports:
    - highspy
  commands:
    - python -m unittest tests/test_highspy.py
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ERGO-Code/HiGHS
  summary: 'High performance serial and parallel solver for large scale sparse linear optimization problems'
  description: |
    HiGHS is a high performance serial and parallel solver for large scale
    sparse linear optimization problems of the form

         min ½ xᵀ Q x + cᵀ x     s.t. L ≤ Ax ≤ U; l ≤ x ≤ u

    where Q must be positive semi-definite and, if Q is zero, there may be a
    requirement that some of the variables take integer values. Thus HiGHS can
    solve linear programming (LP) problems, convex quadratic programming (QP)
    problems, and mixed integer programming (MIP) problems. It is mainly written in
    C++, but also has some C. It has been developed and tested on various Linux,
    MacOS and Windows installations.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://ergo-code.github.io/HiGHS/stable/
  dev_url: https://github.com/ERGO-Code/HiGHS

extra:
  recipe-maintainers:
    - adament
